//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogTranslations.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\E142890\\PanSystem\\Languages\\English\\PanSysData\\Text Files")]
        public string EnglishDirectory {
            get {
                return ((string)(this["EnglishDirectory"]));
            }
            set {
                this["EnglishDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\E142890\\PanSystem\\Languages\\Espanol\\PanSysData\\Text Files")]
        public string TranslationDirectory {
            get {
                return ((string)(this["TranslationDirectory"]));
            }
            set {
                this["TranslationDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\E142890\\Documents\\TranslationStrings.csv")]
        public string OutputFile {
            get {
                return ((string)(this["OutputFile"]));
            }
            set {
                this["OutputFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\E142890\\PanSystem\\Pan1\\Reservoir\\Pan4.0.8\\Resource files")]
        public string CompleteEnglishDirectory {
            get {
                return ((string)(this["CompleteEnglishDirectory"]));
            }
            set {
                this["CompleteEnglishDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\E142890\\PanSystem\\Pan1\\Reservoir\\Pan4.0.8\\Resource files")]
        public string CompleteTranslationDirectory {
            get {
                return ((string)(this["CompleteTranslationDirectory"]));
            }
            set {
                this["CompleteTranslationDirectory"] = value;
            }
        }
    }
}
