//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPressurePlotter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfPressurePlotter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Document&gt;
        ///			&lt;Placemark&gt;
        ///				&lt;name&gt;Bedfordshire&lt;/name&gt;
        ///				&lt;styleUrl&gt;#sn_noicon_copy200&lt;/styleUrl&gt;
        ///				&lt;Polygon&gt;
        ///					&lt;outerBoundaryIs&gt;
        ///						&lt;LinearRing&gt;
        ///							&lt;coordinates&gt;
        ///								-0.3524995000000001,51.8739,0 -0.3524995000000001,51.8713,0 -0.3520005,51.86680000000001,0 -0.3485995,51.8609,0 -0.3458995,51.8575,0 -0.3416005,51.85479999999999,0 -0.3391005,51.8522,0 -0.3381995,51.85090000000001,0 -0.3410005,51.84810000000001,0 -0.3466995,51.845,0 -0.35249950 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CountiesOfEngland {
            get {
                return ResourceManager.GetString("CountiesOfEngland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///  &lt;Document&gt;
        ///    &lt;name&gt;&lt;/name&gt;
        ///    &lt;Placemark&gt;&lt;name&gt;Aruba&lt;/name&gt;&lt;description&gt;ISO_A2=AW : ISO_N3=533.0&lt;/description&gt;&lt;LookAt&gt;&lt;longitude&gt;-69.98267466267889&lt;/longitude&gt;&lt;latitude&gt;12.52088880763951&lt;/latitude&gt;&lt;heading&gt;10.0&lt;/heading&gt;&lt;tilt&gt;10.0&lt;/tilt&gt;&lt;range&gt;700&lt;/range&gt;&lt;/LookAt&gt;&lt;Style&gt;&lt;IconStyle&gt;&lt;color&gt;00ffffff&lt;/color&gt;&lt;scale&gt;0.4&lt;/scale&gt;&lt;Icon&gt;&lt;href&gt;http://icons.opengeo.org/markers/icon-poly.1.png&lt;/href&gt;&lt;/Icon&gt;&lt;/IconStyle&gt;&lt;LabelStyle&gt;&lt;color&gt;00ffffff&lt;/color&gt;&lt;/LabelStyle&gt;&lt;PolySt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string countries_world {
            get {
                return ResourceManager.GetString("countries_world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Document&gt;
        ///&lt;Placemark xmlns=&quot;http://www.opengis.net/kml/2.2&quot;&gt;&lt;name&gt;Aberdeen North&lt;/name&gt;&lt;Polygon&gt;&lt;outerBoundaryIs&gt;&lt;LinearRing&gt;&lt;coordinates&gt;-2.26561174051,57.1483054096,0 -2.25924102907,57.154263723,0 -2.25918062533,57.1543716444,0 -2.25793108376,57.1560459642,0 -2.25745582918,57.1573521758,0 -2.2574017527,57.1574205578,0 -2.25725343844,57.1574873367,0 -2.254519906,57.1583085751,0 -2.25439964267,57.1583690055,0 -2.25427175507,57.1585228748,0 -2.25388872466,57.1593186 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UkConstuencies {
            get {
                return ResourceManager.GetString("UkConstuencies", resourceCulture);
            }
        }
    }
}
